### PR TITLE
Author is MuleSoft

### PR DESCRIPTION
**Pull request by nescalante**

### CODE REVIEW

**Comment by nescalante** [comment]
already there as `"The Advanced REST client authors <arc@mulesoft.com>"`

**Comment by jarrodek** [comment]
Please, don't merge anything into this project without my approval.

**Comment by Narkhip** [comment]
@jarrodek you can use branch protection configuration to make sure nobody merges something without your approval

**Comment by jarrodek** [comment]
I don't have admin.

**Comment by jarrodek** [comment]
Again, please, put my full name into the package definition.

**Comment by Narkhip** [comment]
you can go to #engineering-services and we can create a github team for you (condition is that it should have more than 1 member) and we can make that team a member and approves of the repo. It's just a suggestion

**Comment by jarrodek** [comment]
Thanks Nicolas. I did not know that.

**Pull request merged**
