### PR TITLE
chore: upgrading dependencies (preview)

### PR DESCRIPTION
**Pull request by jarrodek**
- upgraded api-request-panel to the new element (moved to a new repository)
- upgraded api-request-editor to the new element (moved to a new repository)
- upgraded api-url-editor to the new element (moved to a new repository)
- upgraded xhr-simple-request to the new element (moved to a new repository)
- removing `raml-aware` - it is not used anyway

Now the components for the request editor/panel are consolidated in the following repositories:
- advanced-rest-client/api-request
- advanced-rest-client/api-authorization
- advanced-rest-client/api-url
- advanced-rest-client/api-server-selector
- advanced-rest-client/api-headers
- advanced-rest-client/api-forms

The following repositories are deprecated and will be archived after this PR is merged:
- advanced-rest-client/api-property-form-item
- advanced-rest-client/api-headers-editor
- advanced-rest-client/api-headers-form
- advanced-rest-client/api-url-data-model
- advanced-rest-client/api-url-editor
- advanced-rest-client/api-url-params-editor
- advanced-rest-client/api-authorization-method
- advanced-rest-client/xhr-simple-request
- advanced-rest-client/api-request-editor
- advanced-rest-client/api-request-panel

To be discussed:
- What to do with the `api-body-editor`? The components used to build the editor are already deprecated and archived as ARC migrated to new body editor. It is possible to migrate the body editor to extend ARC's editor but ARC's editor is based on Monaco and not CodeMirror. So doing this it would introduce a breaking change and I am not sure if I am ready for a new major release of API Console right now. The ARC's body editor has a configuration option to use code mirror but Monaco's source would be included regardless. It is not problematic in case of API designer as it is already using Monaco, but for other products it would mean a different build. We could potentially build a new API body editor that is not extending the ARC's class but I have no resources to do so right now. 

Other relevant changes:
- The request editor doesn't care about the validation anymore. It reports the invalid state but the request is always sent "as-is" regardless to the validation state. This is cause by the long-lasting problem we have with authorization (especially OAuth) that does not allow to send the HTTP request until a token is assigned. When the API Console is used with the mocking service which potentially can ignore the authorization state, this will allow to make a successful request. For a real endpoint it would return 401 status code. I don't consider this as a breaking change though as this is a minor change in the user flows.
- the components are now using types defined in `advanced-rest-client/arc-types`. It is made this way to consolidate the components and reuse ARC's base components in API Console. Additionally it helps with development process and helps avoiding errors while developing the application.
- Updated dark theme in the demo pages
- Updated the authorization UI to remove the redirect URI field for OAuth2 grant types that do not support redirection.

This is still a preview. The new version is not yet ready. This PR is meant to be backward compatible, though, the sources for the request editor, request panel, and the response panel had changed to match use Advanced REST Client's data structure and reuse the logic.

### CODE REVIEW

**Comment by jarrodek** [comment]
@TwoPlusTwoOne there are tests that are failing but I believe these are your tests. I am not sure, for example, why tests here tests internals of the `api-method-documentation` element. This should be done in the corresponding element.
I'll be working on this throughout the next week.

**Comment by TwoPlusTwoOne** [comment]
@jarrodek yeah, the reason I started adding inner component tests, is because there have been cases where a component changes, and then tests in parent components start failing, but we don't catch them because we aren't running their tests, we're only running the child component's tests.

So I thought concentrating bug-specific tests in this repo would be a good idea to avoid potential problems

**Review by TwoPlusTwoOne — COMMENTED** [review]
Regarding the `api-body-editor`; to see if I'm understanding correctly, for now we can leave it as is and it'll work, but if we need to change something in it, we would necessarily have to migrate it first?

Which repository would it fall into? Or would it fall into its own repository?

I also don't understand the difference between extending ARC's body editor and rewriting the whole thing. Wouldn't either case be a breaking change?

**Comment by jarrodek** [comment]
> if we need to change something in it, we would necessarily have to migrate it first?
Depends on what has to be done. The inner editors are deprecated and archived. The main element is still out there.

I think it would be a new repository to replace all other repositories related to body editing. I guess this would be `api-body-editor` (the base class is `body-editor`). Since such a repository already exists this would be a major upgrade for it.

> I also don't understand the difference between extending ARC's body editor and rewriting the whole thing. Wouldn't either case be a breaking change?

I don't think any of these changes would be a breaking change. The end result of using the body editor is to produce text, file, or FormData. You still have to apply the same AMF model. So even when you rewrite the whole thing the API will be the same.
I suggested extending the ARC's body editor because it has the whole new logic and the UI for HTTP body processing. What its missing is the AMF overlay. It can be a completely new body editor if we choose to do so. I believe that extending ARC's class just makes it simpler to migrate.

**Review by carowright — APPROVED** [review]

**Pull request merged**
