### PR TITLE
Release/6.2.1

### PR DESCRIPTION
**Pull request by jarrodek**
##  Fixes
- Examples generation after AMF model changes (via @api-components/api-example-generator#4.3.0)
- Auto selection of a custom server when no servers are defined in an API (via @api-components/api-server-selector#0.4.2)
- Support for the partial AMF model when querying for servers (via @api-components/amf-helper-mixin#4.1.2)
- `api-request` event listener is now registered on the request panel instead of the `eventsTarget`
- Duplicated `content-type` header on the request editor (via @api-components/api-headers-editor#4.1.1)
- APIC-398 - XSS via authorization URI (via @advanced-rest-client/oauth-authorization#4.0.3)
- APIC-414 - Authorization method styling issue (@advanced-rest-client/authorization-method#0.1.15)
- restored support for partial model when getting servers (amf-helper-mixin#4.1.3)
- cheching for an array value when computing servers servers (amf-helper-mixin#4.1.4)
- APIC-409 - Operation and endpoint servers override base servers when switching to Try It panel in element mode
- APIC-405 - Fix display of enum values for array type document

## Features
- Added OAS' external documentation support in the navigation

## Other
- Updated dev dependencies
- Some components were upgraded to open-wc standards, added typings, updated linting rules

### CODE REVIEW

**Comment by TwoPlusTwoOne** [comment]
- Support for the partial AMF model when querying for servers (via @api-components/api-server-selector#0.4.2)

This is actually via @api-components/amf-helper-mixin#4.1.2

**Comment by jarrodek** [comment]
Thanks @TwoPlusTwoOne. I updated the description

**Comment by TwoPlusTwoOne** [comment]
APIC-409 - Operation and endpoint servers override base servers when switching to Try It panel in element mode.

**Comment by TwoPlusTwoOne** [comment]
I can't finish determining why those tests are failing on Safari. I don't think this should block our release, which should go out today ASAP. @jarrodek @lbauret I want to know your thoughts and see if we can get this out today.

**Comment by lbauret** [comment]
@TwoPlusTwoOne IMHO why don't we release this version ASAP and then we can check what is going on with the failing tests.

**Comment by TwoPlusTwoOne** [comment]
We still need Pawel to merge this with the failing checks, though.

The failing test, in theory, refers to a problem with sever selection changes not propagating correctly up to the api-console, then down to the api-documentation. But it seems strange

**Comment by TwoPlusTwoOne** [comment]
The thing is, manually testing the component in safari, is working fine.

**Comment by lbauret** [comment]
Great then, let's wait for @jarrodek for approval. We really need this version released today

**Comment by jarrodek** [comment]
LGTM. We are gonna deal with Safari issue later.

**Pull request merged**
