### PR TITLE
Display the root description of the API

### PR DESCRIPTION
**Pull request by hadrienk**
Renders the root description of the API on top of the page.

### CODE REVIEW

**Comment by sichvoge** [comment]
Can you add an image that shows the change and also it seems Travis failed as well.

**Comment by hadrienk** [comment]
for the following RAML:

````raml
#%RAML 1.0
title: Method Execution Service API
version: v1
baseUri: /api/
description: |

  Paragraphs are separated by a blank line.

  2nd paragraph. *Italic*, **bold**, and `monospace`. Itemized lists
  look like:

  * this one
  * that one
  * the other one

  Note that --- not considering the asterisk --- the actual text
  content starts at 4-columns in.

  > Block quotes are
  > written like so.
  >
  > They can span multiple paragraphs,
  > if you like.

  Use 3 dashes for an em-dash. Use 2 dashes for ranges (ex., "it's all
  in chapters 12--14"). Three dots ... will be converted to an ellipsis.
  Unicode is supported. ☺
````

The console looks like this: 

image

**Comment by hadrienk** [comment]
I am not sure why the Travis build fails, but it does on the `bower update` phase.

**Comment by sichvoge** [comment]
Not really sure if the description is well placed. The problem might occur if, and only if, the description is very long and you need to scroll down to the actual content. Maybe something like "see more" / "see less" could help to mitigate that?

**Comment by hadrienk** [comment]
Yes, that is a good point. Is there an Angular directive available for this? If not I can code it in the view real quick as well.

**Comment by sichvoge** [comment]
A parameter sounds reasonable. Let me ask @agustinlg if there is an Angular directive, but I don't think so.

**Comment by hadrienk** [comment]
Okay. I will implement that in the view then.

Do you have any idea why the build fails? I can't figure this out.

**Comment by hadrienk** [comment]
I have implemented a simple show more show less link.

**Pull request merged**
