### PR TITLE
Add Dockerfile to run RAML API Console

### PR DESCRIPTION
**Pull request by kokaz**
The `Dockerfile` builds an image that could run the `api-console`
within a container. It provides the required environment to
run the application seamlessly on your machine or server.

Depends on: PR #181 (UTF-8 support for SASS)

### CODE REVIEW

**Comment by dmartinezg** [comment]
The file should be excluded from bower and npm dists.

**Comment by jcenturion** [comment]
@kokaz, Could you please exclude the `Dockerfile` from NPM and bower? So, I can merge it.

**Comment by kokaz** [comment]
@jcenturion @dmartinezg What do you mean by exclude ? I'm not actually a node/bower pro

**Comment by jcenturion** [comment]
@kokaz: Following, you can find a link about this topic:

- https://github.com/bower/bower.json-spec#ignore
- https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by kokaz** [comment]
@jcenturion I think it's OK. Let me know :)

**Comment by jcenturion** [comment]
LGTM. Thanks @kokaz  ;)

@dmartinezg: any other comment?

**Comment by kokaz** [comment]
ping :)

**Comment by dmartinezg** [comment]
Sorry I did not realize, this was waiting for my aproval. :+1: and thanks @kokaz

**Pull request merged**
