### PR TITLE
Fixed problem with custom security schemas

### LINKED ISSUE #145: Console does not perform requests when there is a non-standard auth method
Our raml have a very basic auth included in `securedBy` :

```
- api_key:
    type: x-basic-key
    description: Token in "Authorization" header, value "Bearer <token>". Token defined in application configueration.
```

According to https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#type-1 such config is allowed. When I click e.g. a `GET` button, request to the backend is not performed. In raml console the 'spinning' circle and cancel button appears, but never ends. When I have deleted the `securedBy` suddenly the `GET` works.

### PR DESCRIPTION
**Pull request by psotres**
According to the spec, any "x-{}" schema should work. This should fix #145 and #149. 

Anyway the "Unknown authentication strategy" error that is thrown at "common/client/auth_strategies.js" is still unhandled and that error is not shown anywhere.

### CODE REVIEW

**Comment by sichvoge** [comment]
@psotres did you sign our CLA?

**Comment by jcenturion** [comment]
@psotres LGTM. Have you signed our CLA?

**Comment by jcenturion** [comment]
@psotres: You can find our CLA at https://api-notebook.anypoint.mulesoft.com/notebooks#bc1cf75a0284268407e4.

**Comment by sichvoge** [comment]
@psotres any updates? seems you would also need to merge the current master back to your branch.

**Comment by psotres** [comment]
Sorry, I just signed the CLA. However don't merge this PR, I will send another one with some extra security scheme related bugs fixed.

**Pull request closed without merging**
