### PR TITLE
'Try It' should provide templates based on JSON Schema

### LINKED ISSUE #36: 'Try It' should provide templates based on JSON Schema
We can define the expected request body through RAML and I think that the console could provide some kind of template based on the JSON schema (of course only if some JSON content type is selected).

Example:
I have the following very basic JSON Schema:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "collection_command",
  "description": "Writable collection representation",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    }
  },
  "required": ["name"],
  "additionalProperties": false
}
```

I switch to 'Try It' in the web console and choose `application/json` as my content type. The web console automatically inserts the following basic template:

```
{
  "name": "TODO",
  "description: "TODO (optional)"
}
```

Now I don't propose to go crazy about this and support the vast amount of features that  JSON schema supports, e.g. patternProperties, but a simple template generation for named properties (given the schema type is `object`) is possible.

Thinking further: This could even be extended to other schema types (XML), but I believe that JSON schemas would be a good place to start.

I would be willing to contribute if you find this feature acceptable for the api-console project.

### PR DESCRIPTION
**Pull request by bripkens**
Provide simple examples for the 'try it' section of RAML, based
on the JSON schema to aid RAML users in the API exploration
process.

I am not entirely happy with the logic for schema based example
generation being placed in `BodyType`. I would generally try
to move this to an Angular service, but I wanted to get your
opinion on this first.

Example generation was extracted to a standalone library which is
being used by the api-console:
https://github.com/bripkens/json-template-generator

Contributor agreement signed:
https://gist.github.com/bripkens/f12524c4ce1acd0a0202

Fixes #36

### CODE REVIEW

**Comment by jaoued** [comment]
+1

**Comment by sichvoge** [comment]
@bripkens I am taking care of that currently. To get that merged, can you please sign our CLA and if you have some tests even better so that we can what you have done. If everything is fine, I make sure to merge it.

**Comment by bripkens** [comment]
@sichvoge: See the PR opening message. CLA is signed and tests are included.

**Comment by sichvoge** [comment]
@bripkens Can you resolve the latest conflicts in this PR - I'll make sure to merge it later. Thanks again for contributing.

**Comment by s0undt3ch** [comment]
Whats the status of this feature?

**Comment by bripkens** [comment]
@s0undt3ch: I no longer have a need for this and won't update the PR. The long wait time for a merge resulted in large conflicts, basically rendering this PR useless and requiring a complete rewrite. This was demotivating. Feel free to take the changes and adapt them to the latest `upstream/master`.

**Comment by s0undt3ch** [comment]
Bummer.

**Comment by sichvoge** [comment]
That is really a bummer and completely on us unfortunately. Really sorry for not being as responsive as we should be :( the biggest change happened around RAML 1.0; are you sure that this means to completely rewrite everything you did? @bripkens

**Pull request closed without merging**
