### PR TITLE
Bugs/array type validation error

### PR DESCRIPTION
**Pull request by carowright**
This is the tooltip added to array input. It contains an example of the format that the arrays should be written.

screen shot 2017-04-19 at 1 06 20 pm

### CODE REVIEW

**Comment by carowright** [comment]
@sichvoge Hi Christian. What do you think of the information tooltip for arrays input in the screenshot attached?

**Comment by sichvoge** [comment]
Like it. Is this tooltip consistent with all the other fields like enum, etc?

**Comment by carowright** [comment]
@sichvoge for enums a combo box is shown, and the user can just select from those predefined values

**Comment by sichvoge** [comment]
What I meant is the tooltip! Is there an info button that I can hover and get a tooltip on all fields?

**Pull request merged**
