### PR TITLE
Convert string to JSON for display examples

### PR DESCRIPTION
**Pull request by edentsai**
This commit to fix the error that display examples incorrect (https://github.com/mulesoft/api-console/issues/309).

### CODE REVIEW

**Comment by sichvoge** [comment]
Not really sure why the test is failing. @edentsai @cesaraugustogarcia any idea?

**Comment by edentsai** [comment]
@sichvoge I have no idea, 
but it just passed after I rebase my branch with latest master branch...

**Comment by sichvoge** [comment]
Cool. @cesaraugustogarcia might be able to look at that soon. Thanks @edentsai

**Comment by OlegusTesterovichus** [comment]
Please review this fix.

**Comment by edentsai** [comment]
Just rebase my branch on latest master branch

**Pull request merged**
