### PR TITLE
Fixed multiple minification issues - reserved keywords being used as properties and angularJS directives/controller dependencies being malformed after minification/munging/obfuscation

### PR DESCRIPTION
**Pull request by ravikiranj**
This pull request fixes 2 minification/obfuscation issues.
* Fixes reserved keywords being used as properties by referring to them via strings
* Fixes minification issues w.r.t RAML directives and controllers by providing an array of dependencies and function instead of just the function

RAML Initializer - http://rkjanardhana.com/api-console-dist/
RAML Console (preloaded) - http://rkjanardhana.com/api-console-dist/ramlconsoleapp.html

See Network tab and notice http://rkjanardhana.com/api-console-dist/scripts/api-console-minified-munged.js

### CODE REVIEW

**Comment by blakeembrey** [comment]
@ravikiranj Looks great, thank you! The array fix for minification was very much needed.

I'm just checking (/cc @jcenturion) how the vendor scripts are being copied (https://github.com/mulesoft/node-raml-validate and https://github.com/mulesoft/node-raml-sanitize are two files you changes that aren't part of the repo).

Depending on how those are copied across, we could just automate the ES3ify of those. Maybe we'll even decide to bundle the minified/built files with ES3 compatibility to avoid all the property name changes.

**Comment by ravikiranj** [comment]
I ES3-fied `api-console-vendor.js` locally but since it included from external libs that was concatenated. Unfortunately, I cannot change our JS compressor for the project I'm working on, hence I'll have to deal with local fixes until https://github.com/yui/yuicompressor/issues/47 gets fixed :(

Thanks a bunch for all the help you've offered, the API docs console looks great :) !

P.S: I also hit another issue with YUICompressor with this project, see http://davidwalsh.name/yui-compressor-media-query-error. I had to manually extract the media queries to a new file and patch that in using https://www.npmjs.com/package/media-query-extractor . YUICompressor has not been kind to me the last few days :( ! It might be worth calling these issues out somewhere (maybe README.md?) since other folks who try to minify api-console js/css using YUICompressor will encounter these.

**Comment by jcenturion** [comment]
@ravikiranj: It looks really good. Have you signed our [CLA](https://api-notebook.anypoint.mulesoft.com/notebooks#bc1cf75a0284268407e4)?

**Comment by ravikiranj** [comment]
@jcenturion https://gist.github.com/ravikiranj/da31e0316ead59251c1f

**Comment by jcenturion** [comment]
Thx.

**Comment by jcenturion** [comment]
@ravikiranj: could you please `rebase` against `master` so I can merge this change?

**Pull request merged**
