### PR TITLE
Don't unset credentials when switching endpoints

### PR DESCRIPTION
**Pull request by mseashor**
If multiple secured endpoints exist in an API, it becomes cumbersome to re-enter credentials for every end point when using the API console.

This commit moves the initialization of credentials from the endpoint to the raml directives so credentials will be reused until you reload the page.

This is initial issue post: https://github.com/mulesoft/api-console/issues/180

Example RAML (before, credentials would be blanked out between 'test' and 'test2', now they are stored until page refresh):

    #%RAML 0.8
    title: test
    baseUri: /api
    securitySchemes:
      - basic:
          type: Basic Authentication
    traits:
      - secured:
          securedBy: [ basic ]
    /test:
      get:
        is: [ secured ]
    /test2:
      get:
        is: [ secured ]

### CODE REVIEW

**Comment by pipex** [comment]
I really like this.

I'm testing with the 'resource owner password credentials' scheme and is really annoying to re-fill four fields each time.

I hope it gets merged :)

**Comment by mseashor** [comment]
This should be ready to go.  

I added a test which ensures that two resources will cache credentials.  

FYI: It took me a while to figure out the the tests kept failing because TravisCI runs at a resolution by default that is not wide enough to show the 'Try It' functionality (it's collapsed and user/pass are hidden).  I added another commit which instructs TravisCI to update the default resolution.  I believe this will be helpful for avoiding this confusing issue in the future.  I modeled the fix after TravisCI's recommended way to do this: http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)

**Comment by mseashor** [comment]
Also - I signed the contributors agreement: https://api-notebook.anypoint.mulesoft.com/notebooks#bc1cf75a0284268407e4

**Comment by jcenturion** [comment]
LGTM. :+1: Thx.

**Comment by jcenturion** [comment]
Merging ...

**Pull request merged**
